name: Deploy Papelera Backend to Azure App Service

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install
      working-directory: papelera-back/backend   

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: papecl
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: papelera-back/backend            
