name: Deploy Papelera Backend to Azure App Service

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: 'Run npm install, build, and test'
      working-directory: ./
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Copy frontend files into backend folder
      run: cp -r ./frontend/* ./backend/

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: papecl
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./backend
